ruthe: tried to fix spurious bug when img="", now retrying to fetch,mesage if fail

diff --git a/ruthe b/ruthe
--- a/ruthe
+++ b/ruthe
@@ -1,9 +1,18 @@
 #!/bin/bash
 #
-# What's the current image file
-img=$(curl --no-progress-meter  https://ruthe.de/|grep image_src |sed -E 's/.*(https.*strip_[0-9]*.jpg)">/\1/g') || exit $?
-# and it's name
-[ img = "" ] && echo >2 "curl for ruthe failed - try again" && exit 0
+# What's the current image file ...
+maxtry=3
+while [ -z $img ] && [ $((tries++)) -lt $maxtry ]
+	do
+		sleep $((tries-1))
+		img=$(curl --no-progress-meter  https://ruthe.de/|grep image_src |sed -E 's/.*(https.*strip_[0-9]*.jpg)">/\1/g') || exit $?
+	done
+if [ $tries -gt $maxtry ]; then
+	echo "could not find image on ruthe.de after trying $((--tries)) times - giving up for now"
+	exit $tries
+fi
+
+# ... and it's name
 filnam=$(basename $img)
 
 name="Ruthe"
